### ISSUE TITLE
Images should be resized

### ISSUE THREAD

**Issue by naoliv** [osmfoundation/welcome-mat#15]
Specially important for places where the connection is slow, the frontpage (and maybe somewhere else where images are used) should have their pictures resized.

For example, we need to load a 3.1M image https://osmfoundation.github.io/welcome-mat/images/whatishistory_14665124541_52ce01db2c_o_KLL.jpg just to have it displayed with a size of 374x248

This is even worse when opening it on phones (where the pictures are displayed in even smaller sizer).

**Comment by mikelmaron** [comment]
Oh yea, that's bad. If anyone can post resized images as comments here, or as a pull request, that will help fix this faster.

**Comment by mikelmaron** [comment]
fixed in https://github.com/osmfoundation/welcome-mat/commit/3bbaf4a1c4bf2bdc6efe2063d950e15e22bc5f22
