### ISSUE TITLE
Choice of photos

### ISSUE THREAD

**Issue by imagico** [osmfoundation/welcome-mat#16]
With all six entry page sections now having photos there seems to be an imbalance due to the lack of any field mapping depiction.  The visitor could get the wrong impression that OSM is only about desk work.

I would suggest to replace the _What is OpenStreetMap?_ picture with a field mapping photo.  The photo currently used there could be moved to _How to give back?_ - which, being an active topic, would be more intuitive with a more active illustration.

**Comment by althio** [comment]
This is highly subjective but I found this picture rather peculiar:
https://osmfoundation.github.io/welcome-mat/images/using_osm_taipei.jpg
as it is used right now to illustrate "Working with OpenStreetMap Data".

Indeed if I am new to OSM, all I can see is someone _playing shadow theatre_ (and yes, I see very sharply the shadow of a bird of prey or monster attacking a city with a lot of red on the map for impact points (too much imagination?)) so most definitively not "_Working_ with OpenStreetMap Data"

In the other hand, if I know OSM well, I see someone _explaining and teaching_ OSM (see the tabs for osm.org ; HOT [tasking manager] ; Learn [learnosm.org]), which is at odds with the title "_Working_ with OpenStreetMap Data"

I am a bit sorry for non-constructive feedback and I know how good illustrations are hard to come by.

**Comment by mikelmaron** [comment]
Certainly more thought can be put into the photos. Any specific image recommendations welcome!

**Comment by mikelmaron** [comment]
fixed in https://github.com/osmfoundation/welcome-mat/commit/3bbaf4a1c4bf2bdc6efe2063d950e15e22bc5f22

**Comment by mikelmaron** [comment]
ok, done @imagico

**Comment by imagico** [comment]
Great, thanks.
