### ISSUE TITLE
a "who uses..." suggestion from list-serve

### ISSUE THREAD

**Issue by danbjoseph** [osmfoundation/welcome-mat#31]
from the `osmf-talk` list

> Just want to mention that the Electronic map service, Tianditu, operated by National Geomatics Center of China, also uses OpenStreetMap like the way Baidu maps do.
Maybe you can add it to the list, and here is the link
http://map.tianditu.gov.cn

**Comment by mikelmaron** [comment]
that's for catching this, but duplicating comment already here https://github.com/osmfoundation/welcome-mat/issues/13#issuecomment-443188566

**Comment by danbjoseph** [comment]
oops. sorry. 👍
