### ISSUE TITLE
There should be a link to the Blog (blog.osm.org)

### ISSUE THREAD

**Issue by timwaters** [osmfoundation/welcome-mat#33]
The main OpenStreetMap blog https://blog.openstreetmap.org/ doesn't appear to be linked anywhere except in a minor section about what the Communications Working Group works on.

**Comment by mikelmaron** [comment]
@timwaters where would be good place to include a link? Maybe this page? https://welcome.openstreetmap.org/about-osm-community/osm-news/

PRs welcome

**Comment by timwaters** [comment]
with the PR merged, happily closing this issue
