### ISSUE TITLE
There should be more than one link to the actual project website openstreetmap.org (SEO?)

### ISSUE THREAD

**Issue by timwaters** [osmfoundation/welcome-mat#34]
I could only find one link to the actual openstreetmap.org site in the semi-hidden section which opens when the user clicks the (i) button, where it suggests the user to create a new account there.

There should be more links back to the actual main website for SEO reasons, for discoverability of new users who want to know what OSM is about and for usability of existing users who could want to click back to the main site

**Comment by mikelmaron** [comment]
@timwaters that makes sense. PR with these changes welcome!

**Comment by timwaters** [comment]
I'd be happy to draft a PR with some changes!

**Comment by timwaters** [comment]
with the related PR merged, happily closing this issue
