### ISSUE TITLE
Proof reading

### ISSUE THREAD

**Issue by JohanEntur** [osmfoundation/welcome-mat#41]
I'll just drop a general proof reading issue here:

Regarding https://welcome.openstreetmap.org/working-with-osm-data/how-good-is-osm/
Three places have double spacing:
- "...starting point.  OSM data..."
- "...quality of the map.  Also, in some..."
- "...This is  evidenced by increased..."

I also find the sentence "_The one thing that is certain about OSM, is it is constantly improving in all regions_." to be very strangely formed. In particular the part with "_is it is_". I will not pretend to have a better sounding sentence, but maybe someone else has one.

Further, i believe the three sentences at the end, which are followed by bullet points should all be ended with a colon ( : ). 

Regarding https://welcome.openstreetmap.org/working-with-osm-data/contribute-osm-data/
In this sentence: "The scope is to set expectations on visibility of mapping efforts". Should not _visibility_ be changed to _transparency_? Just a thought.

Regarding https://welcome.openstreetmap.org/working-with-osm-data/research-with-osm/
The phrase "_From Kathmandu to Berlin_" seems very odd, and dated. If its a sort of saying, its certainly not a world wide use-phrase.

**Comment by goldfndr** [comment]
The one thing that is certain about OSM is, in all regions, it is constantly improving.

[or](https://slate.com/human-interest/2011/05/em-dashes-why-writers-should-use-them-more-sparingly.html)

The one thing that is certain about OSM is—in all regions—it is constantly improving.

**Comment by mikelmaron** [comment]
Thanks for the copy edits. Let me know if you have any more specific suggestions
