### ISSUE TITLE
Observations on content

### ISSUE THREAD

**Issue by imagico** [osmfoundation/welcome-mat#5]
[_What is OpenStreetMap?_](https://osmfoundation.github.io/welcome-mat/what-is-openstreetmap/)

* list of features misses addresses which is the third most frequently mapped feature in OSM after buildings and roads.

[_How do we give back?_](https://osmfoundation.github.io/welcome-mat/how-to-give-back/)

* _Why other ways can we contribute?_ - formulation error.
* Data contribution options need to be better described:
  * Direct contributions to the OSM database need to abide by the community rules.
  * There should be a prominent suggestion to release geodata under open licenses.

[_Who uses OpenStreetMap?_](https://osmfoundation.github.io/welcome-mat/about-osm-community/consumers/)

* extreme English language + US bias in selection of organizations
* If such lists are provided there should be objective criteria for inclusion, possibly with reduction in volume through a random selection from a larger list.  Everything else shows favoritism.

[_How can we give money to OpenStreetMap?_](https://osmfoundation.github.io/welcome-mat/about-osm-community/donate-to-osm/)

* I think this is a bit unbalanced in just asking for money but not explaining what the OSMF actually does to deserve this money.  There should be some explanation on what the OSMF mainly does and how the money is spent beyond the [formal organization structure info](https://osmfoundation.github.io/welcome-mat/about-osm-community/working-groups/).

[_How to get in touch_](https://osmfoundation.github.io/welcome-mat/about-osm-community/get-in-touch/)

* prominently mentioning the Advisory board is a problem since there is no spokesperson and the individual members are often likely subject to conflicts of interest in case of specific inquiries from organizations.  Listing the local chapters here instead might be a better idea.
* could also be connected to https://www.openstreetmap.org/help and https://wiki.openstreetmap.org/wiki/Contact_channels

[_Working with OpenStreetMap Data_](https://osmfoundation.github.io/welcome-mat/working-with-osm-data/)

* Content of this section currently lacks any actual info on how to access and work with OSM data.

[_How good is OSM data?_](https://osmfoundation.github.io/welcome-mat/working-with-osm-data/how-good-is-osm/)

* poor choice of external references IMO.  There is some scientific literature in this field and there is also analysis from the community on completeness (like for example addresses) which would deserve to be mentioned here.

[_Organized Editing in OpenStreetMap_](https://osmfoundation.github.io/welcome-mat/working-with-osm-data/contribute-osm-data/)

* this would prejudice work in progress from the OSM community on a directed editing policy so it is inappropriate to have this here.

[_Where do we find a good developer or company to build with OSM?_](https://osmfoundation.github.io/welcome-mat/working-with-osm-data/find-a-developer/)

* seems somewhat needlessly unhelpful.  Most local chapters are used to handling inquiries for help related to OSM - they could be mentioned here.  There is also https://wiki.openstreetmap.org/wiki/Commercial_OSM_Software_and_Services

**Comment by imagico** [comment]
>> this would prejudice work in progress from the OSM community on a directed editing policy so it is inappropriate to have this here.

> This guidance was developed by the Advisory Board and shared publicly previously. We could include a mention here that official policy work is ongoing.

Since it was before my time and there is no mailing list archive i can't reliably prove this but no such advise from the Advisory Board as a whole was ever minuted AFAIK, it was publicly presented as being developed by _members of the advisory board_ and despite the clear intention to present this as the position of the Advisory Board it is frankly unlikely considering the composition at that time that it was the consensus position of the Advisory Board.  It certainly is not the consensus position now ;-)

It would probably be a good idea for the OSMF board to clearly communicate this kind of difference (individual opinions vs. consensus position) to avoid members feeling the need to publicly correct misappropriation of the Advisory Board as a whole by individual members.

So i stand by my opinion that including something like this in an official OSMF document would inappropriately prejudice the community process.  If you want to include something provisional the only appropriate option would be to use the current DWG draft.

**Comment by mikelmaron** [comment]
> So i stand by my opinion 

Thanks for sharing your opinion.

**Comment by imagico** [comment]
> Agree this could be a better, more global list. The intention is to have a list of well known organizations that use OSM. Do you want to take a try at producing something more wide ranging?

Any list i could come up with would probably be biased as well.

A relatively simple solution would be:

* For companies: List all corporate members :wink:
* For the rest: One example per country would be a reasonable approach to ensure some diversity.

**Comment by mikelmaron** [comment]
> Any list i could come up with would probably be biased as well.
> For the rest: One example per country would be a reasonable approach to ensure some diversity.

Well we need something, let's not complicate it.

Sounds like a good starting point. But limiting to one per country is probably going to leave out some great ones, so let's not get too weighted down with this.

**Comment by RobJN** [comment]
Worth noting that this is a document for companies by companies. It would be easy to fall down a load of edge cases and lose a lot of time. 80/20 rule seems good enough here. So for example a simple list of companies that are recognisable is good enough and preferable to an exhausting process where we try to define a complex criteria of what is and isn't included.

>Where do we find a good developer or company to build with OSM?

My local chapter (OSM UK) is planning to link directly to the Welcome Mat and until we have developed our own roster of developers this section is a big plus for us. Even when we have such a roster, I see no harm in the welcome mat also having a list. Ours will focus on local developers so won't be exhaustive.

**Comment by mikelmaron** [comment]
Just want to capture what's remaining from this discussion

## Working with OpenStreetMap Data

> Content of this section currently lacks any actual info on how to access and work with OSM data.

* [ ] We had not done this article previously, since it seemed such a big topic. We'll work on a short starting article on it.

## How good is OSM data?

> poor choice of external references IMO. There is some scientific literature in this field and there is also analysis from the community on completeness (like for example addresses) which would deserve to be mentioned here.

* [ ] If you have a better list of references here, please share it. This is not meant to be comprehensive, but a short list of the best articles as a starting point.

## Where do we find a good developer or company to build with OSM?

> seems somewhat needlessly unhelpful. Most local chapters are used to handling inquiries for help related to OSM - they could be mentioned here. There is also https://wiki.openstreetmap.org/wiki/Commercial_OSM_Software_and_Services

* [ ] Will link to that wiki page. we already mention connecting to local chapters in the article.


## Who uses OpenStreetMap?
> > > If such lists are provided there should be objective criteria for inclusion

> > Agree this could be a better, more global list. The intention is to have a list of well known organizations that use OSM. Do you want to take a try at producing something more wide ranging?

> Any list i could come up with would probably be biased as well.
> For companies: List all corporate members 😉
> For the rest: One example per country would be a reasonable approach to ensure some diversity.

* [ ] Well we need something, let's not complicate it. Sounds like a good starting point. But limiting to one per country is probably going to leave out some great ones, so let's not get too weighted down with this.

**Comment by imagico** [comment]
Regarding _How good is OSM data?_ - i am not very familiar with either the scientific literature in this field or with community projects but there is quite a few literature - just for example look at https://scholar.google.de/scholar?hl=en&q=openstreetmap+data+quality (not all of this is stuff you would want to link to of course - there is a lot of questionable methodology in this field as well).

In terms of community projects there is in particular https://regio-osm.de/hausnummerauswertung/ which comes to mind for addresses.  For completeness in general there is also https://wiki.openstreetmap.org/wiki/Completeness.

I would suggest to inquire the larger OSM community for input on this subject, maybe collect it on a wiki page and condense the most important points in this section.

Regarding _Who uses OpenStreetMap?_ - this should be a cross section of examples, not a ranking of greatness (whatever that means).  Including only large companies would for example seem a bad idea since this would not speak to readers from the SME domain.

Again i am no particular expert in this field so it might be best to reach out to the wider community for collecting a broad spectrum of examples.

**Comment by mikelmaron** [comment]
closing here, opened new tickets to focus on remaining questions
