### ISSUE TITLE
Could the readme link to the live site?

### ISSUE THREAD

**Issue by SomeoneElseOSM** [osmfoundation/welcome-mat#56]
It'd be great if the readme linked to https://welcome.openstreetmap.org somewhere so that organisations wanting to contribute to OSM who do a web search that finds this repository (but not the main site) can immediately link to it.

I've just done something like that and come here.  In my case I know the name of the site, but many people may not if they're new to OSM.

**Comment by mikelmaron** [comment]
Thanks, done

https://github.com/osmfoundation/welcome-mat/blob/gh-pages/README.md
