### ISSUE TITLE
Can't connect to openstreetmap, being blocked.

### ISSUE THREAD

**Issue by TrafficManagementNZ** [osmfoundation/welcome-mat#76]
Our company has multiple users operating from the head office internet connection. It appears we are being blocked from using openstreetmap.org.
How to we get unblocked and stay unblocked please.

**Comment by Firefishy** [comment]
Please could you email operation AT osmfoundation DOT org
Please include you IP address and the URLs for any services you are having issue with.

**Comment by TrafficManagementNZ** [comment]
Hi Team

The below was generated from IP address of 14.1.58.180, however we have had it from other IP’s aswell.
We are using on online service called Submitica (submitica.co.nz), they use openstreetmap.org as part of their system and it’s this that stops working sometimes.

[https://support.thinkproject.com/attachments/token/32oJ8hcmm7twzbVnYdhswKPh3/?name=image001.png]

Kind Regards

Jeff Clarke
Manager
Quality Computer Systems Ltd.
41C Killarney Road
Hamilton

P: 07 847 7308
C: 027 5151993
W: www.qcs.co.nz

[Banner-Email30]

**Comment by Firefishy** [comment]
You are using the Nominatim geocoding service. The nominatim has strictly (auto) enforced usage policy: https://operations.osmfoundation.org/policies/nominatim/
If you do not follow the policy, your app will be temporarily blocked, if you continue the blocks are extended.

It is possible to self host nominatim and other services if your usage requires.

**Comment by TrafficManagementNZ** [comment]
Hi Grant

So from what you are saying, if we try to use the service “too much” like a couple of requests at the same time (an absolute maximum of 1 request per second), then we will get blocked?
It is quite possible we are seen to be doing this as all the users for the company use a Terminal Server, so although they may be from different offices, ie. Different internet connections, but they are all going out through the one at head office.

We would only need a couple to be using it at the same time and we’d be blocked.

Is there anything that can be done about this please.

Kind Regards

Jeff Clarke
Manager
Quality Computer Systems Ltd.
41C Killarney Road
Hamilton

P: 07 847 7308
C: 027 5151993
W: www.qcs.co.nz

[Banner-Email30]
