### ISSUE TITLE
https://welcome.osm.org/ shows sports gambling site instead??

### ISSUE THREAD

**Issue by mnalis** [osmfoundation/welcome-mat#84]
Rationale:
People are expecting that shorted `osm.org` domain works the same as longer `openstreetmap.org` (e.g. `wiki.osm.org`, `osm.org`, `tile.osm.org`, etc).

However, that assumption breaks when I tries to open welcome mat site using `welcome.osm.org` instead of `welcome.openstreetmap.org`.

While `welcome.openstreetmap.org` works normally as expected:
![small_welcome openstreetmap org](https://user-images.githubusercontent.com/156656/212562941-9effdc0e-ffae-442c-b970-92f2cbe9b324.png)

Using shorted `welcome.osm.org` however opens this (Seems to be sports gambling site in Indonesian language or something):
![small_welcome osm org](https://user-images.githubusercontent.com/156656/212562978-a5fce40f-777a-46e1-aac7-54df7be21e00.png)

I find it as a problem which should be fixed. Ideally in the way so https://welcome.osm.org works the same as https://welcome.openstreetmap.org. (failing that, at should visiting the page should throw an error instead of showing random hacked-looking content)

I've tried asking OSM Operations, and they indicated it is probably because  while both DNS servers point to same IP, the web server has only `welcome.openstreetmap.org` name registered, and should have `welcome.osm.org` registered too, so I should report here. They are however not sure if registering more than one name is even possible on github pages where Welcome mat is allegedly hosted.

So, could something be done about that?

I've only found somewhat related https://github.com/osmfoundation/welcome-mat/issues/40 (while also bad, certificate warning was maybe little better that showing random gambling site under official `osm.org` domain)

**Comment by danieldegroot2** [comment]
cc: @Firefishy

**Comment by Firefishy** [comment]
:-( The site uses GitHub Pages and multiple domains are not supported.

**Comment by Firefishy** [comment]
I will fix the issue over next day or 2.

**Comment by craigallan** [comment]
My 2cents on the github multiple domain problem...
Delete the A and AAAA records for welcome.osm.org
welcome.osm.org  CNAME  welcome.openstreetmap.org

**Comment by Firefishy** [comment]
> My 2cents on the github multiple domain problem... Delete the A and AAAA records for welcome.osm.org welcome.osm.org CNAME welcome.openstreetmap.org

We use [code to manage all our domains](https://github.com/openstreetmap/dns). For ease of management, all OpenStreetMap domains use the same config. While we could likely code in specific handling to drop the osm.org records, it would likely be better to fix the issue in another way.

**Comment by Firefishy** [comment]
I have temporarily disabled the invalid DNS records in https://github.com/openstreetmap/dns/commit/996105ef5d12d65f3afd10022934284bb3e81bdb until ultimate fix is deployed: https://github.com/openstreetmap/chef/pull/566

**Comment by Firefishy** [comment]
Fixed now.
